---
title: "dynamic_prediction_plot"
author: "Daniel Christiadi"
date: "Compiled on `r format(Sys.time(), '%d %B, %Y')`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, results = 'asis', collapse = TRUE)

libraries <- c("tidyverse", "data.table", "skimr", "dynpred", "prodlim", 
               "randomForestSRC", "pec", "ggsci", "gt", "patchwork", 
               "cutpointr", "ROCR")

installed <- installed.packages()[,'Package']
new.libs <- libraries[!(libraries %in% installed)]
if(length(new.libs)) install.packages(new.libs,repos="http://cran.csiro.au",
                                      dependencies=TRUE)

lib.ok <- sapply(libraries, require, character.only=TRUE)

seed <- 7
predict_horizon <- 5 #5
landmark <- c(0.5, 1, 1.5, 2, 2.5, 3)
longi_cov <- c("egfr", "haemoglobin", "albumin", "chloride", "glucose") #top 5

# longi_cov <- c("albumin", "alkphos", "bicarb", "calcium", "chloride",
#                 "egfr", "glucose", "haemoglobin", "phosphate", "platelet",
#                 "potassium", "sodium", "wcc") # full

# base_cov <- c("age_init", "sex") #full model
base_cov <- c("age_init")  #Top5 model
```

```{r test set}
train_dt <- read_rds("top5_train_dt.gz")
test_dt <- read_rds("top5_test_dt.gz")
```

```{r rsf_models}
# model_2y <- vector("list", length = length(landmark))
model_5y <- vector("list", length = length(landmark))

for (i in seq_along(landmark)){
    file_name <- str_c(c("full", "model", landmark[i], "landmark_5.gz"), 
                       collapse = "_")
    # file_name <- str_c(c("top5", "model", landmark[i], "landmark_5.gz"), 
    #                    collapse = "_")
    # file_name <- str_c(c("top5", "model", landmark[i], "landmark_2.gz"), 
    #                    collapse = "_")
    print(file_name)
    model_5y[[i]] <- readRDS(file = file_name)
    # model_2y[[i]] <- readRDS(file = file_name)
}

# saveRDS(model_5y, "full_model_5y.gz")
# saveRDS(model_5y, "top5_model_5y.gz") #top5
# saveRDS(model_2y, "model_2y.gz")

# model_2y <- read_rds("model_2y.gz")
# model_5y <- read_rds("top5_model_5y.gz")
model_5y <- read_rds("full_model_5y.gz")
```

```{r dynamic prediction plot}
example_id <- dt %>%
    slice_sample(n = 1) %>%
    pull(id)

# error_id <- fread("error_id.gz")
# error_id <- error_id[,V1]

for (example_id in example_id){
    tryCatch({
    print(glue::glue("Current id: {example_id}"))
    example_dt <- dt %>% 
        filter(id == example_id) %>% 
        select(id, !!base_cov, relyear, !!longi_cov, 
               time_compete:status_compete_num) %>% 
        group_by(id) %>% 
        fill(!!longi_cov) %>% 
        ungroup() %>% 
        as.data.table()
    
    max_test_time <- example_dt %>% 
        slice_max(relyear) %>% 
        mutate(relyear = plyr::round_any(relyear, 0.5, f = floor)) %>% 
        pull(relyear)
    
    lmx_example_dt <- NULL
    
    if (max_test_time > landmark[length(landmark)]){
        for (i in seq_along(landmark)) {
            temp <- cutLM(data = example_dt, outcome = list(time = "time_compete",
                                                  status = "status_compete_num"),
                          LM = landmark[i], horizon = landmark[i] + predict_horizon,
                          covs = list(fixed = base_cov, varying = longi_cov),
                          format = "long", id = "id", rtime = "relyear", 
                          right = FALSE) 
             lmx_example_dt <- rbind(lmx_example_dt, temp)
        }
    } else {
       for (i in 1:match(max_test_time, landmark)) {
            temp <- cutLM(data = example_dt, outcome = list(time = "time_compete",
                                                  status = "status_compete_num"),
                          LM = landmark[i], horizon = landmark[i] + predict_horizon,
                          covs = list(fixed = base_cov, varying = longi_cov),
                          format = "long", id = "id", rtime = "relyear", 
                          right = FALSE) 
            lmx_example_dt <- rbind(lmx_example_dt, temp)
        } 
    }
    
    super_cif_dt <- NULL
    
    if (max_test_time > landmark[length(landmark)]){
        for (index in seq_along(landmark)){
            test_dt <- lmx_example_dt %>% 
                filter(LM == landmark[index])
            
            rsf_prediction <- predict.rfsrc(object = model_5y[[index]],
                                            newdata = test_dt, na.action = "na.impute")
            
            column_cif <- sindex(jump.times = rsf_prediction$time.interest,
                                 eval.times = seq(landmark[index], 
                                                  landmark[index] + predict_horizon, 
                                                  0.25))
            
            column_cif[1] <- 1
            
            cif_dt <- data.table(
                relyear = seq(landmark[index], landmark[index] + predict_horizon, 0.25),
                eskd_cif = rsf_prediction$cif[, column_cif, "CIF.1"],
                death_cif = rsf_prediction$cif[, column_cif, "CIF.2"]
            )
            
            super_cif_dt <- rbind(super_cif_dt, cif_dt)
        }
    } else {
        for (index in 1:match(max_test_time, landmark)) {
            test_dt <- lmx_example_dt %>% 
                filter(LM == landmark[index])
            
            rsf_prediction <- predict.rfsrc(object = model_5y[[index]],
                                            newdata = test_dt, na.action = "na.impute")
            
            column_cif <- sindex(jump.times = rsf_prediction$time.interest,
                                 eval.times = seq(landmark[index], 
                                                  landmark[index] + predict_horizon, 
                                                  0.25))
            
            column_cif[1] <- 1
            
            cif_dt <- data.table(
                relyear = seq(landmark[index], landmark[index] + predict_horizon, 0.25),
                eskd_cif = rsf_prediction$cif[, column_cif, "CIF.1"],
                death_cif = rsf_prediction$cif[, column_cif, "CIF.2"]
            )
            
            super_cif_dt <- rbind(super_cif_dt, cif_dt)
        }
    }
    
    super_cif_dt <- super_cif_dt %>% 
        group_by(relyear) %>% 
        summarise(mean_eskd_cif = mean(eskd_cif),
                  mean_death_cif = mean(death_cif))
    
    if (max_test_time > landmark[length(landmark)]){
        example_dt <- example_dt %>% 
            filter(relyear < landmark[6])
    } else {
        example_dt <- example_dt %>% 
            filter(relyear <= (max_test_time + 0.5))
    }
    
    #gt() of example patient
    example_dt %>%
        select(age_init:relyear, !!longi_cov, time_compete:status_compete) %>%
        rename("Intial_age" = age_init,
               "Test_time" = relyear,
               "Event_time" = time_compete,
               "Status" = status_compete) %>%
        gt() %>%
        tab_header(title = md("**Example Patient**")) %>%
        tab_spanner(label = "Pathology Test",
                    columns = !!longi_cov)
        
    longi_plot <- example_dt %>% 
        select(relyear, !!longi_cov) %>% 
        pivot_longer(cols = !!longi_cov, names_to = "test", values_to = "value") %>% 
        ggplot(aes(x = relyear, y = value)) + geom_point() + geom_line() + 
        theme_bw() + 
        facet_grid(test ~., switch = "y", scales = "free_y",
                   labeller = as_labeller(c(albumin = "sAlb (g/L)", 
                                            chloride = "Chloride (mmol/L)",
                                            egfr = "eGFR (mL/min/1.73m2)",
                                            glucose = "Glucose (mmol/L)",
                                            haemoglobin = "Hb (g/L)"))) + 
        labs(y = NULL, x = NULL)
    
    if (max_test_time > landmark[length(landmark)]){
        surv_plot <- super_cif_dt %>% 
            pivot_longer(cols = -relyear,
                         names_to = "event",
                         values_to = "value") %>% 
            ggplot(aes(x = relyear, y = value, colour = event)) + geom_line() + 
            scale_y_continuous(position = "right", labels = scales::label_percent()) +
            scale_colour_nejm(breaks = c("mean_death_cif", "mean_eskd_cif"), 
                                name = "Event CIF", 
                                labels = c("Death", "ESKD")) +
            labs(x = NULL, y = NULL) + 
            coord_cartesian(xlim = c(3, 8)) + 
            theme(legend.position = c(0.53,0.7)) + theme_bw()
    } else {
        surv_plot <- super_cif_dt %>% 
            pivot_longer(cols = -relyear,
                         names_to = "event",
                         values_to = "value") %>% 
            ggplot(aes(x = relyear, y = value, colour = event)) + geom_line() + 
            scale_y_continuous(position = "right", labels = scales::label_percent()) +
            scale_colour_nejm(breaks = c("mean_death_cif", "mean_eskd_cif"), 
                                name = "Event CIF", 
                                labels = c("Death", "ESKD")) +
            labs(x = NULL, y = NULL) + 
            coord_cartesian(xlim = c(max_test_time, 8)) + 
            theme(legend.position = c(0.53,0.7)) + theme_bw()
    }
        
    relyear_lab <- "Time (years)"
    p_lab <- ggplot() + 
        annotate(geom = "text", x = 1, y = 1, label = relyear_lab) + 
        coord_cartesian(clip = "off") + theme_void()
    
    dynamic_plot <- (longi_plot | surv_plot) / p_lab + 
        plot_annotation(title = "Dynamic Plot Prediction") + 
        plot_layout(heights = c(1,0.0075))
    
    file_name <- str_c(c(example_id, ".png"), collapse = "")
        ggsave(filename = file_name, plot = dynamic_plot, width = 16, height = 9,
           units = "in")
    }, error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
}
```





