---
title: "Exploratory Data Analysis"
author: "Daniel Christiadi"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, results = 'asis', collapse = TRUE)
libraries <- c('tidyverse', 'janitor', 'skimr', 'heatmaply', 'data.table', 
               'gtsummary', 'lubridate')
installed <- installed.packages()[,'Package']
new.libs <- libraries[!(libraries %in% installed)]
if(length(new.libs)) install.packages(new.libs,repos="http://cran.csiro.au",
                                      dependencies=TRUE)
lib.ok <- sapply(libraries, require, character.only=TRUE)
```

## Demographic Characteristic

```{r}
dt <- read_rds("dense3.RDS")

dt %>% 
    distinct(id, .keep_all = TRUE) %>% 
    select(sex, age_init, gn, value_egfr_init, status_compete) %>% 
    tbl_summary(label = list(sex ~ "Gender", age_init ~ "Age at Presentation", 
                             gn ~ "GN Diagnosis", 
                             value_egfr_init ~ "Initial eGFR (mL/min/1.73m2)",
                             status_compete ~ "Events")) %>% 
    modify_header(label ~ "**Variable**")
```

## 
