---
title: "dynamic_plot"
author: "Daniel Christiadi"
date: "Compiled on `r format(Sys.time(), '%d %B, %Y')`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, results = 'asis', collapse = TRUE)

libraries <- c("tidyverse", "data.table", "skimr", "dynpred", "prodlim", 
               "randomForestSRC", "pec", "ggsci", "gt", "patchwork", "cutpointr")

installed <- installed.packages()[,'Package']
new.libs <- libraries[!(libraries %in% installed)]
if(length(new.libs)) install.packages(new.libs,repos="http://cran.csiro.au",
                                      dependencies=TRUE)

lib.ok <- sapply(libraries, require, character.only=TRUE)

seed <- 7
predict_horizon <- 5 #5
landmark <- c(0.5, 1, 1.5, 2, 2.5, 3)
longi_cov <- c("egfr", "haemoglobin", "albumin", "chloride", "glucose")
base_cov <- c("age_init")
```

```{r test set}
dt <- read_rds("test_dt.gz")
```

```{r rsf_models}
model_2y <- vector("list", length = length(landmark))
# model_5y <- vector("list", length = length(landmark))

for (i in seq_along(landmark)){
    file_name <- str_c(c("model", landmark[i], "landmark_2.gz"), 
                       collapse = "_")
    # file_name <- str_c(c("model", landmark[i], "landmark_5.gz"), 
    #                    collapse = "_")
    print(file_name)
    model_2y[[i]] <- readRDS(file = file_name)
    # model_5y[[i]] <- readRDS(file = file_name)
}

# saveRDS(model_5y, "model_5y.gz")
# saveRDS(model_2y, "model_2y.gz")
model_5y <- read_rds("model_5y.gz")
model_2y <- read_rds("model_2y.gz")
```

```{r dynamic prediction}
example_id <- dt %>% 
    slice_sample(n = 1) %>% 
    pull(id)

example_dt <- dt %>% 
    filter(id == example_id) %>% 
    select(id, !!base_cov, relyear, !!longi_cov, 
           time_compete:status_compete_num) %>% 
    group_by(id) %>% 
    fill(!!longi_cov) %>% 
    ungroup() %>% 
    as.data.table()

max_test_time <- example_dt %>% 
    slice_max(relyear) %>% 
    mutate(relyear = plyr::round_any(relyear, 0.5, f = floor)) %>% 
    pull(relyear)

lmx_example_dt <- NULL

if (max_test_time > landmark[length(landmark)]){
    for (i in seq_along(landmark)) {
        temp <- cutLM(data = example_dt, outcome = list(time = "time_compete",
                                              status = "status_compete_num"),
                      LM = landmark[i], horizon = landmark[i] + predict_horizon,
                      covs = list(fixed = base_cov, varying = longi_cov),
                      format = "long", id = "id", rtime = "relyear", 
                      right = FALSE) 
         lmx_example_dt <- rbind(lmx_example_dt, temp)
    }
} else {
   for (i in 1:match(max_test_time, landmark)) {
        temp <- cutLM(data = example_dt, outcome = list(time = "time_compete",
                                              status = "status_compete_num"),
                      LM = landmark[i], horizon = landmark[i] + predict_horizon,
                      covs = list(fixed = base_cov, varying = longi_cov),
                      format = "long", id = "id", rtime = "relyear", 
                      right = FALSE) 
         lmx_example_dt <- rbind(lmx_example_dt, temp)
    } 
}

super_cif_dt <- NULL

if (max_test_time > landmark[length(landmark)]){
    for (index in seq_along(landmark)){
        test_dt <- lmx_example_dt %>% 
            filter(LM == landmark[index])
        
        rsf_prediction <- predict.rfsrc(object = model_5y[[index]],
                                        newdata = test_dt, na.action = "na.impute")
        
        column_cif <- sindex(jump.times = rsf_prediction$time.interest,
                             eval.times = seq(landmark[index], 
                                              landmark[index] + predict_horizon, 
                                              0.25))
        
        column_cif[1] <- 1
        
        cif_dt <- data.table(
            relyear = seq(landmark[index], landmark[index] + predict_horizon, 0.25),
            eskd_cif = rsf_prediction$cif[, column_cif, "CIF.1"],
            death_cif = rsf_prediction$cif[, column_cif, "CIF.2"]
        )
        
        super_cif_dt <- rbind(super_cif_dt, cif_dt)
    }
} else {
    for (index in 1:match(max_test_time, landmark)) {
        test_dt <- lmx_example_dt %>% 
            filter(LM == landmark[index])
        
        rsf_prediction <- predict.rfsrc(object = model_5y[[index]],
                                        newdata = test_dt, na.action = "na.impute")
        
        column_cif <- sindex(jump.times = rsf_prediction$time.interest,
                             eval.times = seq(landmark[index], 
                                              landmark[index] + predict_horizon, 
                                              0.25))
        
        column_cif[1] <- 1
        
        cif_dt <- data.table(
            relyear = seq(landmark[index], landmark[index] + predict_horizon, 0.25),
            eskd_cif = rsf_prediction$cif[, column_cif, "CIF.1"],
            death_cif = rsf_prediction$cif[, column_cif, "CIF.2"]
        )
        
        super_cif_dt <- rbind(super_cif_dt, cif_dt)
    }
}

super_cif_dt <- super_cif_dt %>% 
    group_by(relyear) %>% 
    summarise(mean_eskd_cif = mean(eskd_cif),
              mean_death_cif = mean(death_cif))

if (max_test_time > landmark[length(landmark)]){
    example_dt <- example_dt %>% 
        filter(relyear < landmark[6])
} else {
    example_dt <- example_dt %>% 
        filter(relyear <= max_test_time)
}

example_dt %>% 
    select(age_init:relyear, !!longi_cov, time_compete:status_compete) %>% 
    rename("Intial_age" = age_init, 
           "Test_time" = relyear,
           "Event_time" = time_compete,
           "Status" = status_compete) %>% 
    gt() %>%
    tab_header(title = md("**Example Patient**")) %>% 
    tab_spanner(label = "Pathology Test",
                columns = !!longi_cov)
    
longi_plot <- example_dt %>% 
    select(relyear, !!longi_cov) %>% 
    pivot_longer(cols = !!longi_cov, names_to = "test", values_to = "value") %>% 
    ggplot(aes(x = relyear, y = value)) + geom_point() + geom_line() + 
    theme_bw() + 
    facet_grid(test ~., switch = "y", scales = "free_y",
               labeller = as_labeller(c(albumin = "sAlb (g/L)", 
                                        chloride = "Chloride (mmol/L)",
                                        egfr = "eGFR (mL/min/1.73m2)",
                                        glucose = "Glucose (mmol/L)",
                                        haemoglobin = "Hb (g/L)"))) + 
    labs(y = NULL, x = NULL)

if (max_test_time > landmark[length(landmark)]){
    surv_plot <- super_cif_dt %>% 
        pivot_longer(cols = -relyear,
                     names_to = "event",
                     values_to = "value") %>% 
        ggplot(aes(x = relyear, y = value, colour = event)) + geom_line() + 
        scale_y_continuous(position = "right", labels = scales::label_percent()) +
        scale_colour_nejm(breaks = c("mean_death_cif", "mean_eskd_cif"), 
                            name = "Event CIF", 
                            labels = c("Death", "ESKD")) +
        labs(x = NULL, y = NULL) + 
        coord_cartesian(xlim = c(3, 8)) + 
        theme(legend.position = c(0.53,0.7)) + theme_bw()
} else {
    surv_plot <- super_cif_dt %>% 
        pivot_longer(cols = -relyear,
                     names_to = "event",
                     values_to = "value") %>% 
        ggplot(aes(x = relyear, y = value, colour = event)) + geom_line() + 
        scale_y_continuous(position = "right", labels = scales::label_percent()) +
        scale_colour_nejm(breaks = c("mean_death_cif", "mean_eskd_cif"), 
                            name = "Event CIF", 
                            labels = c("Death", "ESKD")) +
        labs(x = NULL, y = NULL) + 
        coord_cartesian(xlim = c(max_test_time, 8)) + 
        theme(legend.position = c(0.53,0.7)) + theme_bw()
}
    
relyear_lab <- "Time (years)"
p_lab <- ggplot() + 
    annotate(geom = "text", x = 1, y = 1, label = relyear_lab) + 
    coord_cartesian(clip = "off") + theme_void()

(longi_plot | surv_plot) / p_lab + 
    plot_annotation(title = "Dynamic Plot Prediction") + 
    plot_layout(heights = c(1,0.0075))

```

```{r correlation}
test_dt <- dt %>% 
    select(id, !!base_cov, relyear, !!longi_cov, 
           time_compete:status_compete_num) %>% 
    group_by(id) %>% 
    fill(!!longi_cov) %>% 
    ungroup() %>% 
    as.data.table()

lmx_test_dt <- NULL

for (i in seq_along(landmark)) {
    temp <- cutLM(data = test_dt, outcome = list(time = "time_compete",
                                          status = "status_compete_num"),
                  LM = landmark[i], horizon = landmark[i] + predict_horizon,
                  covs = list(fixed = base_cov, varying = longi_cov),
                  format = "long", id = "id", rtime = "relyear", 
                  right = FALSE) 
     lmx_test_dt <- rbind(lmx_test_dt, temp)
}

lmx_test_dt <- lmx_test_dt %>% 
    select(-(time_compete:status_compete_num))

super_eskd_cif <- NULL
super_death_cif <- NULL

index <- 1
# for (index in seq_along(landmark)){
    temp  <- lmx_test_dt %>% 
        filter(LM == landmark[index])
    
    # rsf_prediction <- predict.rfsrc(object = model_2y[[index]],
    #                                 newdata = temp, na.action = "na.impute")
    
    rsf_prediction <- predict.rfsrc(object = model_5y[[index]],
                                    newdata = temp, na.action = "na.impute")
    
    column_cif <- sindex(jump.times = rsf_prediction$time.interest,
                         eval.times = seq(landmark[index], 
                                          landmark[index] + predict_horizon, 
                                          0.25))
    
    column_cif[1] <- 1
    eskd_cif <- data.table(id = temp$id)
    
    eskd_cif[, c(as.character(seq(landmark[index], landmark[index] + predict_horizon, 0.25))) := as.data.table(rsf_prediction$cif[, column_cif, "CIF.1"])]
    
    eskd_cif <- melt(eskd_cif, id.vars = c("id"), 
         variable.name = "relyear",
         value.name = "cif")
    
    super_eskd_cif <- rbind(super_eskd_cif, eskd_cif)
    
    death_cif <- data.table(id = temp$id)
    
    death_cif[, c(as.character(seq(landmark[index], landmark[index] + predict_horizon, 0.25))) := as.data.table(rsf_prediction$cif[, column_cif, "CIF.2"])]
    
    death_cif <- melt(death_cif, id.vars = c("id"), 
         variable.name = "relyear",
         value.name = "cif")
    
    super_death_cif <- rbind(super_death_cif, death_cif)
# }

eskd_name <- str_c(c("super_eskd_cif", predict_horizon),
                   collapse = "_")

file_name <- str_c(c(eskd_name, ".gz"), collapse = "")
fwrite(super_eskd_cif, file_name)

death_name <- str_c(c("super_death_cif", predict_horizon),
                   collapse = "_")

file_name <- str_c(c(death_name, ".gz"), collapse = "")
fwrite(super_death_cif, file_name)
```

```{r eskd_cif_analysis}
super_eskd_cif2 <- fread("super_eskd_cif_2.gz")
super_eskd_cif5 <- fread("super_eskd_cif_5.gz")
super_death_cif2 <- fread("super_death_cif_2.gz")
super_death_cif5 <- fread("super_death_cif_5.gz")

super_eskd_cif <- super_eskd_cif5
super_death_cif <- super_death_cif5

super_eskd_cif <- super_eskd_cif %>% 
    arrange(id, relyear) %>% 
    group_by(id, relyear) %>%
    summarise(mean_cif = 100*mean(cif), .groups = "keep") %>% 
    ungroup() %>% 
    group_by(id) %>% 
    mutate(relyear_ahead = lead(relyear),
           mean_cif_ahead = lead(mean_cif),
           slope = (mean_cif_ahead - mean_cif)/(relyear_ahead - relyear)) %>% 
    ungroup() %>% 
    left_join(select(dt, id, time_compete:status_compete), by = "id") %>%  
    distinct(id, relyear, .keep_all = TRUE) %>% 
    arrange(id, relyear) %>% 
    select(id, relyear:mean_cif, slope, time_compete:status_compete)
    
eskd_strict <- super_eskd_cif %>% 
    mutate(time_compete = plyr::round_any(time_compete, 0.25, f = floor)) %>% 
    mutate(event = if_else(
        condition = relyear == time_compete & status_compete == "eskd",
        true = 1,
        false = 0
    )) %>% 
    filter(time_compete >= 3) %>% 
    select(mean_cif: slope, event)

eskd_free <- super_eskd_cif %>%
    mutate(time_compete = plyr::round_any(time_compete, 0.25, f = floor)) %>%
    mutate(upper_limit = time_compete + 0.5,
           lower_limit = time_compete - 0.5) %>%
    mutate(event_early = if_else(
        condition = between(relyear, lower_limit, time_compete) & status_compete == "eskd",
        true = 1,
        false = 0
    )) %>% 
    mutate(event_gen = if_else(
        condition = between(relyear, lower_limit, upper_limit) & status_compete == "eskd",
        true = 1,
        false = 0
    )) %>% 
    filter(time_compete >= 3)

eskd_analysis <- NULL
set.seed(seed)

eskd_strict_youden <- multi_cutpointr(eskd_strict, 
                           class = "event", na.rm = TRUE,
                           method = maximize_metric, metric = youden,
                           boot_runs = 1000)

eskd_analysis <- eskd_strict_youden %>% 
    add_metric(list(ppv, npv)) %>% 
    mutate(method = "youden") %>% 
    select(method, predictor, optimal_cutpoint, acc, AUC, sensitivity, specificity,
           ppv, npv) %>% 
    bind_rows(eskd_analysis)

eskd_strict_f1 <- multi_cutpointr(eskd_strict, 
                           class = "event", na.rm = TRUE,
                           method = maximize_metric, metric = F1_score,
                           boot_runs = 1000)

eskd_analysis <- eskd_strict_f1 %>% 
    add_metric(list(ppv, npv)) %>% 
    mutate(method = "f1") %>% 
    select(method, predictor, optimal_cutpoint, acc, AUC, sensitivity, specificity,
           ppv, npv) %>% 
    bind_rows(eskd_analysis)

eskd_strict_ppvnpv <- multi_cutpointr(eskd_strict, 
                           class = "event", na.rm = TRUE,
                           method = maximize_metric, metric = sum_ppv_npv,
                           boot_runs = 1000)

eskd_analysis <- eskd_strict_ppvnpv %>% 
    add_metric(list(ppv, npv)) %>% 
    mutate(method = "ppv_npv") %>% 
    select(method, predictor, optimal_cutpoint, acc, AUC, sensitivity, specificity,
           ppv, npv) %>% 
    bind_rows(eskd_analysis)

eskd_analysis <- eskd_analysis %>% 
    mutate(dataset = "strict") %>% 
    relocate(dataset, .before = method) %>% 
    arrange(predictor, method)

eskd_early <- eskd_free %>% 
    select(mean_cif, slope, event_early)

eskd_early_youden <- multi_cutpointr(eskd_early, 
                           class = "event_early", na.rm = TRUE,
                           method = maximize_metric, metric = youden,
                           boot_runs = 1000)

eskd_analysis <- eskd_early_youden %>% 
    add_metric(list(ppv, npv)) %>% 
    mutate(method = "youden") %>% 
    select(method, predictor, optimal_cutpoint, acc, AUC, sensitivity, specificity,
           ppv, npv) %>% 
    mutate(dataset = "early") %>% 
    relocate(dataset, .before = method) %>% 
    bind_rows(eskd_analysis)

eskd_early_f1 <- multi_cutpointr(eskd_early, 
                           class = "event_early", na.rm = TRUE,
                           method = maximize_metric, metric = F1_score,
                           boot_runs = 1000)

eskd_analysis <- eskd_early_f1 %>% 
    add_metric(list(ppv, npv)) %>% 
    mutate(method = "f1") %>% 
    select(method, predictor, optimal_cutpoint, acc, AUC, sensitivity, specificity,
           ppv, npv) %>% 
    mutate(dataset = "early") %>% 
    relocate(dataset, .before = method) %>% 
    bind_rows(eskd_analysis)

eskd_early_ppvnpv <- multi_cutpointr(eskd_early, 
                           class = "event_early", na.rm = TRUE,
                           method = maximize_metric, metric = sum_ppv_npv,
                           boot_runs = 1000)

eskd_analysis <- eskd_early_ppvnpv %>% 
    add_metric(list(ppv, npv)) %>% 
    mutate(method = "ppv_npv") %>% 
    select(method, predictor, optimal_cutpoint, acc, AUC, sensitivity, specificity,
           ppv, npv) %>% 
    mutate(dataset = "early") %>% 
    relocate(dataset, .before = method) %>% 
    bind_rows(eskd_analysis)

eskd_range <- eskd_free %>% 
    select(mean_cif, slope, event_gen)

eskd_range_youden <- multi_cutpointr(eskd_range, 
                           class = "event_gen", na.rm = TRUE,
                           method = maximize_metric, metric = youden,
                           boot_runs = 1000)

eskd_analysis <- eskd_range_youden %>% 
    add_metric(list(ppv, npv)) %>% 
    mutate(method = "youden") %>% 
    select(method, predictor, optimal_cutpoint, acc, AUC, sensitivity, specificity,
           ppv, npv) %>% 
    mutate(dataset = "range") %>% 
    relocate(dataset, .before = method) %>% 
    bind_rows(eskd_analysis)

eskd_range_f1 <- multi_cutpointr(eskd_range, 
                           class = "event_gen", na.rm = TRUE,
                           method = maximize_metric, metric = F1_score,
                           boot_runs = 1000)

eskd_analysis <- eskd_range_f1 %>% 
    add_metric(list(ppv, npv)) %>% 
    mutate(method = "f1") %>% 
    select(method, predictor, optimal_cutpoint, acc, AUC, sensitivity, specificity,
           ppv, npv) %>% 
    mutate(dataset = "range") %>% 
    relocate(dataset, .before = method) %>% 
    bind_rows(eskd_analysis)

eskd_range_ppvnpv <- multi_cutpointr(eskd_range, 
                           class = "event_gen", na.rm = TRUE,
                           method = maximize_metric, metric = sum_ppv_npv,
                           boot_runs = 1000)

eskd_analysis <- eskd_range_ppvnpv %>% 
    add_metric(list(ppv, npv)) %>% 
    mutate(method = "ppv_npv") %>% 
    select(method, predictor, optimal_cutpoint, acc, AUC, sensitivity, specificity,
           ppv, npv) %>% 
    mutate(dataset = "range") %>% 
    relocate(dataset, .before = method) %>% 
    bind_rows(eskd_analysis)

eskd_analysis <- eskd_analysis %>% 
    arrange(predictor, method, dataset)

file_name <- str_c(c("eskd_analysis", ".gz"), collapse = "")
fwrite(eskd_analysis, file_name)
```

```{r death_cif_analysis}
super_death_cif <- super_death_cif %>% 
    arrange(id, relyear) %>% 
    group_by(id, relyear) %>%
    summarise(mean_cif = 100*mean(cif), .groups = "keep") %>% 
    ungroup() %>% 
    group_by(id) %>% 
    mutate(relyear_ahead = lead(relyear),
           mean_cif_ahead = lead(mean_cif),
           slope = (mean_cif_ahead - mean_cif)/(relyear_ahead - relyear)) %>% 
    ungroup() %>% 
    left_join(select(dt, id, time_compete:status_compete), by = "id") %>%  
    distinct(id, relyear, .keep_all = TRUE) %>% 
    arrange(id, relyear) %>% 
    select(id, relyear:mean_cif, slope, time_compete:status_compete)

death_strict <- super_death_cif %>% 
    mutate(time_compete = plyr::round_any(time_compete, 0.25, f = floor)) %>% 
    mutate(event = if_else(
        condition = relyear == time_compete & status_compete == "death",
        true = 1,
        false = 0
    )) %>% 
    filter(time_compete >= 3) %>% 
    select(mean_cif: slope, event)

death_free <- super_death_cif %>%
    mutate(time_compete = plyr::round_any(time_compete, 0.25, f = floor)) %>%
    mutate(upper_limit = time_compete + 0.5,
           lower_limit = time_compete - 0.5) %>%
    mutate(event_early = if_else(
        condition = between(relyear, lower_limit, time_compete) & status_compete == "death",
        true = 1,
        false = 0
    )) %>% 
    mutate(event_gen = if_else(
        condition = between(relyear, lower_limit, upper_limit) & status_compete == "death",
        true = 1,
        false = 0
    )) %>% 
    filter(time_compete >= 3)

death_analysis <- NULL
set.seed(seed)

death_strict_youden <- multi_cutpointr(death_strict, 
                           class = "event", na.rm = TRUE,
                           method = maximize_metric, metric = youden,
                           boot_runs = 1000)

death_analysis <- death_strict_youden %>% 
    add_metric(list(ppv, npv)) %>% 
    mutate(method = "youden") %>% 
    select(method, predictor, optimal_cutpoint, acc, AUC, sensitivity, specificity,
           ppv, npv) %>% 
    bind_rows(death_analysis)

death_strict_f1 <- multi_cutpointr(death_strict, 
                           class = "event", na.rm = TRUE,
                           method = maximize_metric, metric = F1_score,
                           boot_runs = 1000)

death_analysis <- death_strict_f1 %>% 
    add_metric(list(ppv, npv)) %>% 
    mutate(method = "f1") %>% 
    select(method, predictor, optimal_cutpoint, acc, AUC, sensitivity, specificity,
           ppv, npv) %>% 
    bind_rows(death_analysis)

death_strict_ppvnpv <- multi_cutpointr(death_strict, 
                           class = "event", na.rm = TRUE,
                           method = maximize_metric, metric = sum_ppv_npv,
                           boot_runs = 1000)

death_analysis <- death_strict_ppvnpv %>% 
    add_metric(list(ppv, npv)) %>% 
    mutate(method = "ppv_npv") %>% 
    select(method, predictor, optimal_cutpoint, acc, AUC, sensitivity, specificity,
           ppv, npv) %>% 
    bind_rows(death_analysis)

death_analysis <- death_analysis %>% 
    mutate(dataset = "strict") %>% 
    relocate(dataset, .before = method) %>% 
    arrange(predictor, method)

death_early <- death_free %>% 
    select(mean_cif, slope, event_early)

death_early_youden <- multi_cutpointr(death_early, 
                           class = "event_early", na.rm = TRUE,
                           method = maximize_metric, metric = youden,
                           boot_runs = 1000)

death_analysis <- death_early_youden %>% 
    add_metric(list(ppv, npv)) %>% 
    mutate(method = "youden") %>% 
    select(method, predictor, optimal_cutpoint, acc, AUC, sensitivity, specificity,
           ppv, npv) %>% 
    mutate(dataset = "early") %>% 
    relocate(dataset, .before = method) %>% 
    bind_rows(death_analysis)

death_early_f1 <- multi_cutpointr(death_early, 
                           class = "event_early", na.rm = TRUE,
                           method = maximize_metric, metric = F1_score,
                           boot_runs = 1000)

death_analysis <- death_early_f1 %>% 
    add_metric(list(ppv, npv)) %>% 
    mutate(method = "f1") %>% 
    select(method, predictor, optimal_cutpoint, acc, AUC, sensitivity, specificity,
           ppv, npv) %>% 
    mutate(dataset = "early") %>% 
    relocate(dataset, .before = method) %>% 
    bind_rows(death_analysis)

death_early_ppvnpv <- multi_cutpointr(death_early, 
                           class = "event_early", na.rm = TRUE,
                           method = maximize_metric, metric = sum_ppv_npv,
                           boot_runs = 1000)

death_analysis <- death_early_ppvnpv %>% 
    add_metric(list(ppv, npv)) %>% 
    mutate(method = "ppv_npv") %>% 
    select(method, predictor, optimal_cutpoint, acc, AUC, sensitivity, specificity,
           ppv, npv) %>% 
    mutate(dataset = "early") %>% 
    relocate(dataset, .before = method) %>% 
    bind_rows(death_analysis)

death_range <- death_free %>% 
    select(mean_cif, slope, event_gen)

death_range_youden <- multi_cutpointr(death_range, 
                           class = "event_gen", na.rm = TRUE,
                           method = maximize_metric, metric = youden,
                           boot_runs = 1000)

death_analysis <- death_range_youden %>% 
    add_metric(list(ppv, npv)) %>% 
    mutate(method = "youden") %>% 
    select(method, predictor, optimal_cutpoint, acc, AUC, sensitivity, specificity,
           ppv, npv) %>% 
    mutate(dataset = "range") %>% 
    relocate(dataset, .before = method) %>% 
    bind_rows(death_analysis)

death_range_f1 <- multi_cutpointr(death_range, 
                           class = "event_gen", na.rm = TRUE,
                           method = maximize_metric, metric = F1_score,
                           boot_runs = 1000)

death_analysis <- death_range_f1 %>% 
    add_metric(list(ppv, npv)) %>% 
    mutate(method = "f1") %>% 
    select(method, predictor, optimal_cutpoint, acc, AUC, sensitivity, specificity,
           ppv, npv) %>% 
    mutate(dataset = "range") %>% 
    relocate(dataset, .before = method) %>% 
    bind_rows(death_analysis)

death_range_ppvnpv <- multi_cutpointr(death_range, 
                           class = "event_gen", na.rm = TRUE,
                           method = maximize_metric, metric = sum_ppv_npv,
                           boot_runs = 1000)

death_analysis <- death_range_ppvnpv %>% 
    add_metric(list(ppv, npv)) %>% 
    mutate(method = "ppv_npv") %>% 
    select(method, predictor, optimal_cutpoint, acc, AUC, sensitivity, specificity,
           ppv, npv) %>% 
    mutate(dataset = "range") %>% 
    relocate(dataset, .before = method) %>% 
    bind_rows(death_analysis)

death_analysis <- death_analysis %>% 
    arrange(predictor, method, dataset)

file_name <- str_c(c("death_analysis", ".gz"), collapse = "")
fwrite(death_analysis, file_name)
```

