---
title: "training"
author: "Daniel Christiadi"
date: 
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, results = 'asis', collapse = TRUE)
libraries <- c("tidyverse", 'data.table', 'skimr', "mice", "JMbayes2")
installed <- installed.packages()[,'Package']
new.libs <- libraries[!(libraries %in% installed)]
if(length(new.libs)) install.packages(new.libs,repos="http://cran.csiro.au",
                                      dependencies=TRUE)
lib.ok <- sapply(libraries, require, character.only=TRUE)

cross_val <- 5
seed <- 7
```

```{r cross-validation}
dt <- readRDS("tangri3.RDS")

# Replacing unlikely value of albumin/creatinine ratio == 0 (4 IDs)
dt <- dt %>% 
    mutate(value = replace(value, 
                           test == "albcreat_ratio" & value == 0, 0.1),
           sex = factor(sex,levels = c("Female", "Male"))) 

short_dt <- dt %>% 
    select(id, value_egfr_init, sex:gn, time_eskd:status_compete) %>% 
    distinct() %>% 
    mutate(gn = replace(gn, gn != "no", "yes"),
           gn = factor(gn, levels = c("no", "yes")))

set.seed(seed)
folds <- rsample::vfold_cv(short_dt, v = cross_val, strata = "time_compete")
train1_dt <- folds$splits[[1]] %>% rsample::analysis() 
test1_dt <- folds$splits[[1]] %>% rsample::assessment()

longtrain1_dt <- dt %>% 
    filter(id %in% train1_dt$id) %>%
    select(id:relyear)
```

```{r imputation}
dt <- longtrain1_dt %>% 
    pivot_wider(id_cols = c("id", "relyear"),
                names_from = test,
                values_from = value)

impute_dt <- dt %>% 
    filter(relyear == 0)
temp_dt <- mice(impute_dt, m = 1, maxit = 50, method = "pmm", seed = seed)
impute_dt <- complete(temp_dt)

longtrain1_dt <- impute_dt %>% 
    pivot_longer(cols = albumin:postural_hr,
                 names_to = "test",
                 values_to = "value") %>% 
    bind_rows(longtrain1_dt) %>% 
    arrange(id, relyear, test) %>% 
    distinct()
```
Due to infinity of survival model coefficient for MCD and FG/ITG (gn diagnosis) due to minimal or no event, the gn diagnosis was collapsed into yes/no. Following further analysis, there was no significant interaction between sex/age_init or sex/gn. However, there was significant interaction between gn/age_init.
```{r survival model}
train1_dtCR <- train1_dt %>% 
    select(-time_eskd, -status_eskd) %>% 
    mutate(status_compete = factor(status_compete, levels = c(0, 1, 2),
                                   labels = c("censored", "eskd", "death"))) %>% 
    JMbayes2::crisk_setup(data = .,
                          statusVar = "status_compete",
                          censLevel = "censored",
                          nameStrata = "CR")

jm_surv_model <- coxph(Surv(time = time_compete, event = status2) ~ 
                        (value_egfr_init + sex + age_init)*strata(CR), 
                    data = train1_dtCR)

summary(jm_surv_model)
```

```{r longitudinal covariates}
longtrain1_dt <- longtrain1_dt %>% 
    left_join(select(train1_dt, id:gn), by = "id") %>% 
    pivot_wider(id_cols = c("id", "relyear", "sex", "age_init", "gn"),
                names_from = test,
                values_from = value) %>%
    fill(adjca:weight)
```

```{r function to create base linear model}
model0 <- function(y_name, dataset){
    lmm_formula <- reformulate(termlabels = "relyear" ,
                               response = y_name, intercept = TRUE)
    lme(lmm_formula,
        random = ~ relyear|id,
        data = dataset, na.action = na.omit,
        )
}
# 
# model1 <- function(y_name, dataset){
#     group_variables <- c("relyear", "age_init", "sex", "gn")
#     lmm_formula <- reformulate(termlabels = group_variables ,
#                                response = y_name, intercept = TRUE)
#     lme(lmm_formula, 
#         random = ~ relyear|id,
#         data = dataset, na.action = na.omit,
#         control = list(maxIter = 100, opt = "optim")
#         )
# }
# 
# model2 <- function(y_name, dataset){
#     group_variables <- c("relyear", "age_init", "sex", "gn", "relyear:age_init",
#                          "relyear:sex", "relyear:gn")
#     lmm_formula <- reformulate(termlabels = group_variables ,
#                                response = y_name, intercept = TRUE)
#     lme(lmm_formula, 
#         random = ~ relyear|id,
#         data = dataset, na.action = na.omit,
#         control = list(maxIter = 100, opt = "optim")
#         )
# }
# 
# model3 <- function(y_name, dataset){
#     group_variables <- c("relyear", "I(relyear^2)", "I(relyear^3)", 
#                          "age_init", "sex", "gn", 
#                          "relyear:age_init","relyear:sex", "relyear:gn")
#     lmm_formula <- reformulate(termlabels = group_variables ,
#                                response = y_name, intercept = TRUE)
#     lme(lmm_formula, 
#         random = ~ relyear|id,
#         data = dataset, na.action = na.omit,
#         control = list(maxIter = 100, opt = "optim")
#         )
# }
```

```{r exploring individual mixed model}
albcreat_model <- lme(log(albcreat_ratio) ~ relyear + I(relyear^2) + 
                          I(relyear^3) + age_init + gn + relyear:age_init +
                          relyear:gn, random = ~relyear|id, 
                      data = longtrain1_dt, na.action = na.omit,
                       control = list(maxIter = 100, opt = "optim"))

albumin_model <- lme(albumin ~ relyear + I(relyear^2)+ age_init + gn +
                      relyear:age_init + relyear:gn + sex + relyear:sex,
                       random = ~relyear|id, data = longtrain1_dt, 
                     na.action = na.omit, 
                       control = list(maxIter = 100, opt = "optim"))

adjca_model <- lme(adjca ~ relyear + age_init + gn +
                      relyear:age_init + relyear:gn + sex + relyear:sex,
                       random = ~relyear|id, data = longtrain1_dt, 
                       control = list(maxIter = 100, opt = "optim"))

phosphate_model <- lme(phosphate ~ relyear + I(relyear^2)+ age_init + gn +
                      relyear:age_init + relyear:gn + sex + relyear:sex,
                       random = ~relyear|id, data = longtrain1_dt,
                       control = list(maxIter = 100, opt = "optim"))

bicarb_model <- lme(bicarb ~ relyear + I(relyear^2)+ age_init + gn +
                      relyear:age_init + relyear:gn + sex + relyear:sex,
                       random = ~relyear|id, data = longtrain1_dt, 
                    na.action = na.exclude,
                       control = list(maxIter = 100, opt = "optim"))

egfr_model <- lme(egfr ~ relyear + I(relyear^2) + age_init + relyear:age_init +
                      sex + relyear:sex, random = ~relyear|id, 
                  data = longtrain1_dt, na.action = na.exclude,
                  control = list(maxIter = 100, opt = "optim"))
```

```{r base joint model}
base_CR_forms <- list(
    "bicarb" = ~ value(bicarb):CR,
    "egfr" = ~ value(egfr):CR)

joint_model_tangri <- jm(Surv_object = jm_surv_model,
                       Mixed_objects = list(bicarb_model, 
                                            egfr_model),
                       time_var = "relyear",
                       functional_forms = base_CR_forms, 
                       n_iter = 25000L, n_burnin = 5000L, n_thin = 5L)
```
