---
title: "landmarking_locf"
author: "Daniel Christiadi"
date: "Compiled on `r format(Sys.time(), '%d %B, %Y')`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, results = 'asis', collapse = TRUE)
libraries <- c("tidyverse", "data.table", "skimr", "nlme", "rsample", 
               "dynpred", "prodlim", "mice", "randomForestSRC", "pec", 
               "gtsummary")
installed <- installed.packages()[,'Package']
new.libs <- libraries[!(libraries %in% installed)]
if(length(new.libs)) install.packages(new.libs,repos="http://cran.csiro.au",
                                      dependencies=TRUE)
lib.ok <- sapply(libraries, require, character.only=TRUE)

cross_val <- 5
seed <- 7
predict_horizon <- 5 #2
landmark <- c(0.5, 1, 1.5, 2, 2.5, 3)

# full model # r/o: "urea", "creatinine"
# longi_cov <- c("albumin", "alkphos", "bicarb", "calcium", "chloride",
#                 "egfr", "glucose", "haemoglobin", "phosphate", "platelet",
#                 "potassium", "sodium", "wcc") 

# longi_cov <- c("albumin", "alkphos", "chloride", "egfr", "haemoglobin", "phosphate",
#                 "potassium", "sodium", "wcc") # Top 10

# longi_cov <- c("albumin", "chloride", "egfr", "haemoglobin", "sodium") # Top 6
longi_cov <- c("albumin", "chloride", "egfr", "haemoglobin") # Top 5

# full model # r/o: "value_egfr_init"
# base_cov <- c("sex", "age_init", "gn_cat")  
base_cov <- c("age_init") # reduced model
```

```{r k-fold}
dt <- read_rds("dense3.RDS")

dt <- dcast(dt, 
      id + relyear + value_egfr_init + sex + age_init + gn_cat + time_compete +
          status_compete ~ test, value.var = "value")

dt <- dt %>% 
    mutate(status_compete_num = case_when(
      status_compete == "censored" ~ 0,
      status_compete == "eskd" ~ 1,
      TRUE ~ 2
    )) %>% 
    relocate(status_compete_num, .after = status_compete) %>% 
    mutate(sex = factor(sex, levels = c("Female", "Male")),
           gn_cat = factor(gn_cat, levels = c("no", "yes")))

set.seed(seed)

folds <- dt %>% 
    select(id, value_egfr_init:status_compete) %>% 
    distinct(id, .keep_all = TRUE) %>% 
    rsample::vfold_cv(v = cross_val, strata = "status_compete")
```

```{r cross validation}
cv_vimp <- NULL
cv_performance <- NULL

for (fold in 1:cross_val){
    print(glue::glue("Current fold: {fold}"))
    
    train_id <- folds$splits[[fold]] %>% 
        rsample::analysis() %>% 
        pull(id)
    
    test_id <- folds$splits[[fold]] %>% 
        rsample::assessment() %>% 
        pull(id)
    
    train_dt <- dt[id %chin% train_id,]
    test_dt <- dt[id %chin% test_id,]
    
    long_train <- train_dt %>%
        select(id, relyear, !!longi_cov)
 
    ## imputing covariates at relyear == 0   
    impute_dt <- long_train %>% 
        filter(relyear == 0)
    
    temp_dt <- mice(impute_dt, m = 1, maxit = 50, method = "pmm", seed = seed)
    impute_dt <- complete(temp_dt)

    train_dt <- impute_dt %>% 
        bind_rows(long_train) %>% 
        arrange(id) %>% 
        distinct(id, relyear, .keep_all = TRUE) %>%
        group_by(id) %>%
        fill(!!longi_cov) %>% 
        ungroup() %>% 
        left_join(select(train_dt, id:status_compete_num),
                  by = c("id", "relyear")) %>% 
        arrange(id, relyear) %>% 
        as.data.table()
    
    test_dt <- test_dt %>% 
        group_by(id) %>% 
        fill(!!longi_cov) %>% 
        ungroup() %>% 
        as.data.table()
    
    train_super_dt <- NULL
    
    for (i in seq_along(landmark)) {
        temp <- cutLM(data = train_dt, outcome = list(time = "time_compete",
                                              status = "status_compete_num"),
                      LM = landmark[i], horizon = landmark[i] + predict_horizon,
                      covs = list(fixed = base_cov, varying = longi_cov),
                      format = "long", id = "id", rtime = "relyear", 
                      right = FALSE) 
        train_super_dt <- rbind(train_super_dt, temp)
    }

    test_super_dt <- NULL

    for (i in seq_along(landmark)) {
        temp <- cutLM(data = test_dt, outcome = list(time = "time_compete",
                                              status = "status_compete_num"),
                      LM = landmark[i], horizon = landmark[i] + predict_horizon,
                      covs = list(fixed = base_cov, varying = longi_cov),
                      format = "long", id = "id", rtime = "relyear", 
                      right = FALSE) 
      test_super_dt <- rbind(test_super_dt, temp)
    }
    
    model_vimp <- NULL
    model_performance <- NULL
    
    for (lmx in landmark){
        print(glue::glue("Processing landmark: {lmx}"))
    
        train_lm <- train_super_dt %>% 
            filter(LM == lmx)
    
        test_lm <- test_super_dt %>% 
            filter(LM == lmx) %>% 
            drop_na()
    
        model_formula <- as.formula(str_c("Surv(time_compete, status_compete_num)",
                       str_c(c(base_cov, longi_cov), collapse = " + "), 
                       sep = "~"))
    
        tune_rsf <- tune.rfsrc(model_formula, data = train_lm, 
               ntreeTry = 500, nodesizeTry = c(1:9, seq(10, 100, 5)))
    
        rsf_model <- rfsrc(formula = model_formula, data = train_lm, ntree = 1000, 
              splitrule = "logrankCR", importance = TRUE, statistics = TRUE, 
              mtry = tune_rsf$optimal[[2]], nodesize = tune_rsf$optimal[[1]])
    
        vimp_temp <- data.table(LM = lmx,
                            event = c("eskd", "death"))
    
        vimp_temp <- cbind(vimp_temp, 100*t(rsf_model$importance))
        model_vimp <- rbind(model_vimp, vimp_temp)
    
        rsf_prediction <- predict.rfsrc(object = rsf_model,
                             newdata = test_lm, na.action = "na.omit")
    
        brier_eskd <- pec(rsf_model, formula = model_formula, data = test_lm,
                         cause = 1)
    
        brier_death <- pec(rsf_model, formula = model_formula, data = test_lm,
                         cause = 2)
    
        error_temp <- unname(apply(rsf_prediction$err.rate, 2, mean, na.rm = TRUE))
        
        performance_temp <- data.table(LM = lmx,
                                       N = rsf_prediction$n,
                                       error_eskd = 100 * error_temp[1],
                                       error_death = 100 * error_temp[2],
                                       brier_eskd = crps(brier_eskd)[2],
                                       brier_death = crps(brier_death)[2])
    
        model_performance <- rbind(model_performance, performance_temp)
    }
    
    model_vimp$fold <- fold
    cv_vimp <- rbind(cv_vimp, model_vimp)
    
    model_performance$fold <- fold
    cv_performance <- rbind(cv_performance, model_performance)
}

# vimp_name <- str_c(c("cv_locf_vimp", predict_horizon), collapse = "_")
# vimp_file_name <- str_c(c(vimp_name, ".gz"), collapse = "")
# fwrite(cv_vimp, file = vimp_file_name)

# performance_name <- str_c(c("cv_locf_performance", predict_horizon), 
#                           collapse = "_")
# performance_name <- str_c(c("cv_locf_performance_top10", predict_horizon), 
#                           collapse = "_")
# performance_name <- str_c(c("cv_locf_performance_top6", predict_horizon),
#                           collapse = "_")
performance_name <- str_c(c("cv_locf_performance_top5", predict_horizon),
                          collapse = "_")
performance_file_name <- str_c(c(performance_name, ".gz"), collapse = "")
fwrite(cv_performance, file = performance_file_name)
```

```{r EDA}
filled_dt <- dt %>% 
    group_by(id) %>% 
    fill(all_of(longi_cov)) %>% 
    ungroup()

filled_dt <- filled_dt %>% 
    select(id, relyear, sex:status_compete_num, !!longi_cov) %>% 
    as.data.table()

super_filled5_dt <- NULL

for (i in seq_along(landmark)) {
        temp <- cutLM(data = filled_dt, outcome = list(time = "time_compete",
                                              status = "status_compete_num"),
                      LM = landmark[i], horizon = landmark[i] + predict_horizon,
                      covs = list(fixed = base_cov, varying = longi_cov),
                      format = "long", id = "id", rtime = "relyear", 
                      right = FALSE) 
      super_filled5_dt <- rbind(super_filled5_dt, temp)
}

super_filled5_dt <- super_filled5_dt %>% 
    mutate(status_compete = case_when(
        status_compete_num == 0 ~ "censored",
        status_compete_num == 1 ~ "eskd",
        TRUE ~ "death"
    )) %>% 
    mutate(status_compete = factor(status_compete, 
                                   levels = c("censored", "eskd", "death"),
                                   labels = c("Censored", "ESKD", "Death")))

theme_gtsummary_journal(journal = "nejm")

for (lmx in landmark){
    
    file_name <- str_c(c("landmark"), lmx, c(".html"), sep = "_")
    print(file_name)
    
    super_filled5_dt %>%
        filter(LM == !!lmx) %>%
        select(-(id:sex), -gn_cat, -(relyear:LM)) %>%
        tbl_summary(
            by = "status_compete",
            missing = "no",
            label = list(age_init ~ "Initial age at presentation")
        ) %>% as_gt() %>% 
        gt::gtsave(file_name)
        
}
```

```{r final model}
predict_horizon <- 5 #2

# longi_cov <- c("egfr", "haemoglobin", "albumin", "chloride", "glucose") #Top5 model
longi_cov <- c("albumin", "alkphos", "bicarb", "calcium", "chloride",
                "egfr", "glucose", "haemoglobin", "phosphate", "platelet",
                "potassium", "sodium", "wcc")
# base_cov <- c("age_init") #Top5 model
base_cov <- c("age_init", "sex")

fold <- 2

train_id <- folds$splits[[fold]] %>% 
        rsample::analysis() %>% 
        pull(id)
    
test_id <- folds$splits[[fold]] %>% 
        rsample::assessment() %>% 
        pull(id)
    
train_dt <- dt[id %chin% train_id,]
test_dt <- dt[id %chin% test_id,]

long_train <- train_dt %>% 
    select(id, relyear, !!longi_cov)

impute_dt <- long_train %>% 
    filter(relyear == 0)

temp_dt <- mice(impute_dt, m = 1, maxit = 50, method = "pmm", seed = seed)
impute_dt <- complete(temp_dt)

train_dt <- impute_dt %>% 
    bind_rows(long_train) %>% 
    arrange(id) %>% 
    distinct(id, relyear, .keep_all = TRUE) %>% 
    group_by(id) %>% 
    fill(!!longi_cov) %>% 
    ungroup() %>% 
    left_join(select(train_dt, id:status_compete_num),
              by = c("id", "relyear")) %>% 
    arrange(id, relyear) %>% 
    as.data.table() 

saveRDS(train_dt, "full_train_dt.gz")
# saveRDS(train_dt, "top5_train_dt.gz")  
train_super_dt <- NULL
    
for (i in seq_along(landmark)) {
    temp <- cutLM(data = train_dt, outcome = list(time = "time_compete",
                                          status = "status_compete_num"),
                  LM = landmark[i], horizon = landmark[i] + predict_horizon,
                  covs = list(fixed = base_cov, varying = longi_cov),
                  format = "long", id = "id", rtime = "relyear", 
                  right = FALSE) 
    train_super_dt <- rbind(train_super_dt, temp)
}

test_dt <- test_dt %>%
    group_by(id) %>%
    fill(!!longi_cov) %>%
    ungroup() %>% as.data.table()

saveRDS(test_dt, "full_test_dt.gz")
# saveRDS(test_dt, "top5_test_dt.gz")

set.seed(seed = seed)

for (lmx in landmark){
    print(glue::glue("Processing landmark: {lmx}"))

    temp_dt <- train_super_dt %>% 
        filter(LM == lmx)

    model_formula <- as.formula(str_c("Surv(time_compete, status_compete_num)",
                   str_c(c(base_cov, longi_cov), collapse = " + "), 
                   sep = "~"))

    tune_rsf <- tune.rfsrc(model_formula, data = temp_dt, 
                           ntreeTry = 500, 
                           nodesizeTry = c(1:9, seq(10, 100, 5)))
    
    print(tune_rsf$optimal)

    rsf_model <- rfsrc(formula = model_formula, data = temp_dt, ntree = 1000, 
          mtry = tune_rsf$optimal[[2]], nodesize = tune_rsf$optimal[[1]], 
          seed = seed)
    
    model_name <- str_c(c("full", "model", lmx, "landmark", predict_horizon), 
                        collapse = "_")
    
    # model_name <- str_c(c("top5", "model", lmx, "landmark", predict_horizon), 
    #                     collapse = "_") #top5
    
    file_name <- str_c(c(model_name, ".gz"), collapse = "")
    saveRDS(rsf_model, file = file_name)
}
```

```{r model lists}
# model_2y <- vector("list", length = length(landmark))
model_5y <- vector("list", length = length(landmark))

for (i in seq_along(landmark)){
    file_name <- str_c(c("full", "model", landmark[i], "landmark_5.gz"), 
                       collapse = "_")
    # file_name <- str_c(c("top5", "model", landmark[i], "landmark_5.gz"), 
    #                    collapse = "_")
    # file_name <- str_c(c("top5", "model", landmark[i], "landmark_2.gz"), 
    #                    collapse = "_")
    print(file_name)
    model_5y[[i]] <- readRDS(file = file_name)
    # model_2y[[i]] <- readRDS(file = file_name)
}

# saveRDS(model_5y, "full_model_5y.gz")
# saveRDS(model_5y, "top5_model_5y.gz") #top5
# saveRDS(model_2y, "model_2y.gz")

# model_2y <- read_rds("model_2y.gz")
# model_5y <- read_rds("top5_model_5y.gz")
model_5y <- read_rds("full_model_5y.gz")
```

```{r train_cif}
predict_horizon <- 5 #2
super_eskd_cif <- NULL
super_death_cif <- NULL

for (index in seq_along(landmark)){
    temp <- train_super_dt %>% 
        filter(LM == landmark[index])
    
    # column_cif <- sindex(jump.times = model_2y[[index]]$time.interest,
    #                      eval.times = seq(landmark[index], 
    #                                       landmark[index] + predict_horizon, 
    #                                       0.25))
    
    column_cif <- sindex(jump.times = model_5y[[index]]$time.interest,
                         eval.times = seq(landmark[index],
                                          landmark[index] + predict_horizon,
                                          0.25))
    
    column_cif[1] <- 1
    eskd_cif <- data.table(id = temp$id)
    
    rsf_prediction <- predict.rfsrc(object = model_5y[[index]],
                                    newdata = temp, na.action = "na.impute")
    
    eskd_cif[, c(as.character(seq(landmark[index], landmark[index] + predict_horizon, 0.25))) := as.data.table(rsf_prediction$cif[, column_cif, "CIF.1"])]
    
    eskd_cif <- melt(eskd_cif, id.vars = c("id"), 
         variable.name = "relyear",
         value.name = "cif")
    
    super_eskd_cif <- rbind(super_eskd_cif, eskd_cif)
    
    death_cif <- data.table(id = temp$id)
    
    death_cif[, c(as.character(seq(landmark[index], landmark[index] + predict_horizon, 0.25))) := as.data.table(rsf_prediction$cif[, column_cif, "CIF.2"])]
    
    death_cif <- melt(death_cif, id.vars = c("id"), 
         variable.name = "relyear",
         value.name = "cif")
    
    super_death_cif <- rbind(super_death_cif, death_cif)
}

eskd_name <- str_c(c("full", "train_eskd_cif", predict_horizon),
                   collapse = "_")
# eskd_name <- str_c(c("top5", "train_eskd_cif", predict_horizon),
#                    collapse = "_")

file_name <- str_c(c(eskd_name, ".gz"), collapse = "")
fwrite(super_eskd_cif, file_name)

death_name <- str_c(c("full", "train_death_cif", predict_horizon),
                   collapse = "_")
# death_name <- str_c(c("top5", "train_death_cif", predict_horizon),
#                    collapse = "_")

file_name <- str_c(c(death_name, ".gz"), collapse = "")
fwrite(super_death_cif, file_name)
```

```{r test_cif}
predict_horizon <- 5 #2

test_dt <- test_dt %>% 
    select(id, !!base_cov, relyear, !!longi_cov, 
           time_compete:status_compete_num) %>% 
    group_by(id) %>% 
    fill(!!longi_cov) %>% 
    ungroup() %>% 
    as.data.table()

lmx_test_dt <- NULL

for (i in seq_along(landmark)) {
    temp <- cutLM(data = test_dt, outcome = list(time = "time_compete",
                                          status = "status_compete_num"),
                  LM = landmark[i], horizon = landmark[i] + predict_horizon,
                  covs = list(fixed = base_cov, varying = longi_cov),
                  format = "long", id = "id", rtime = "relyear", 
                  right = FALSE) 
     lmx_test_dt <- rbind(lmx_test_dt, temp)
}

lmx_test_dt <- lmx_test_dt %>% 
    arrange(id, LM)

lmx_test_dt <- lmx_test_dt %>% 
    select(-(time_compete:status_compete_num))

super_eskd_cif <- NULL
super_death_cif <- NULL

for (index in seq_along(landmark)){
    temp  <- lmx_test_dt %>% 
        filter(LM == landmark[index])
    
    # rsf_prediction <- predict.rfsrc(object = model_2y[[index]],
    #                                 newdata = temp, na.action = "na.impute")
    
    rsf_prediction <- predict.rfsrc(object = model_5y[[index]],
                                    newdata = temp, na.action = "na.impute")
    
    column_cif <- sindex(jump.times = rsf_prediction$time.interest,
                         eval.times = seq(landmark[index], 
                                          landmark[index] + predict_horizon, 
                                          0.25))
    
    column_cif[1] <- 1
    eskd_cif <- data.table(id = temp$id)
    
    eskd_cif[, c(as.character(seq(landmark[index], landmark[index] + predict_horizon, 0.25))) := as.data.table(rsf_prediction$cif[, column_cif, "CIF.1"])]
    
    eskd_cif <- melt(eskd_cif, id.vars = c("id"), 
         variable.name = "relyear",
         value.name = "cif")
    
    super_eskd_cif <- rbind(super_eskd_cif, eskd_cif)
    
    death_cif <- data.table(id = temp$id)
    
    death_cif[, c(as.character(seq(landmark[index], landmark[index] + predict_horizon, 0.25))) := as.data.table(rsf_prediction$cif[, column_cif, "CIF.2"])]
    
    death_cif <- melt(death_cif, id.vars = c("id"), 
         variable.name = "relyear",
         value.name = "cif")
    
    super_death_cif <- rbind(super_death_cif, death_cif)
}

eskd_name <- str_c(c("full", "test_eskd_cif", predict_horizon),
                   collapse = "_")
# eskd_name <- str_c(c("top5", "test_eskd_cif", predict_horizon),
#                    collapse = "_")
file_name <- str_c(c(eskd_name, ".gz"), collapse = "")
fwrite(super_eskd_cif, file_name)

death_name <- str_c(c("full", "test_death_cif", predict_horizon),
                   collapse = "_")
# death_name <- str_c(c("top5", "test_death_cif", predict_horizon),
#                    collapse = "_")
file_name <- str_c(c(death_name, ".gz"), collapse = "")
fwrite(super_death_cif, file_name)
```
